version: "3.8"

services:
  nginx:
    image: alonecat/photo-stock-nginx:latest
    deploy:
      replicas: 1
    ports:
      - "80:80"
    networks:
      - nuxt-network
    depends_on:
      - nuxt-app

  nuxt-app:
    image: alonecat/photo-stock-frontend:latest
    deploy:
      replicas: 1
    ports:
      - "3000:3000"
    networks:
      - nuxt-network
    environment:
      NODE_ENV: production
      GRAPHQL_URL: /run/secrets/graphql_url
    secrets:
      - graphql_url

networks:
  nuxt-network:
    driver: overlay

secrets:
  graphql_url:
    external: true
