version: "3.3"

services:
  nginx:
    networks:
      - nuxt-network
    ports:
      - "80:80"
    restart: unless-stopped
    depends_on:
      nuxt-app:
        condition: service_started

  nuxt-app:
    ports:
      - "3000:3000"
    networks:
      - nuxt-network
    environment:
      NODE_ENV: ${NODE_ENV}
      GRAPHQL_URL: ${GRAPHQL_URL}

networks:
  nuxt-network:
    driver: bridge
