version: "3.3"

services:
  nginx:
    image: alonecat/photo-stock-nginx:latest
    networks:
      - nuxt-network
    ports:
      - "80:80"
    depends_on:
      - nuxt-app

  nuxt-app:
    image: alonecat/photo-stock-frontend:latest
    ports:
      - "3000:3000"
    networks:
      - nuxt-network
    environment:
      NODE_ENV: production
    secrets:
      - graphql_url

networks:
  nuxt-network:
    driver: overlay

secrets:
  graphql_url:
    external: true
