name: frontend-dev

services:
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: unless-stopped
    develop:
      watch:
        - action: sync+restart
          path: ./
          target: /etc/nginx

  nuxt-app:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: npm run dev
    ports:
      - "3000:3000"
      - "24678:24678"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      NODE_ENV: 'development'
