services:
  nginx:
    image: alonecat/photo-stock-nginx:latest
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    ports:
      - "80:80"
    networks:
      - nuxt-network

  nuxt-app:
    image: alonecat/photo-stock-frontend:latest
    restart: always
    deploy:
      replicas: 1
      restart_policy:
        condition: any
    environment:
      NODE_ENV: ${NODE_ENV}
      GRAPHQL_URL: ${GRAPHQL_URL}
    ports:
      - "3000:3000"
    networks:
      - nuxt-network

networks:
  nuxt-network:
    driver: overlay