name: Deploy Docker stack

on:
  push:
    branches: ['main']

jobs:
  deploy_stack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}

      - name: Set up docker context over SSH authentication
        uses: amirmarmul/docker-context-ssh-action@v1
        with:
          ssh-host: ${{ secrets.SSH_HOST }}
          ssh-username: ${{ secrets.SSH_USERNAME }}
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Inspect docker context
        run: |
          docker context ls -q
          docker context use remote

      - name: Deploy Docker stack
        run: |
          docker stack deploy -c docker-compose.yml my_stack
