name: Publish Docker image

on:
  push:
    branches: ['main']

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub

    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Create .env file
        env:
          GQL_HOST: "http://persons-web-1.local/wp/graphql"

        run: |
          touch .env
          echo "GQL_HOST=\"$GQL_HOST\"" >> .env
          echo "APP_PORT=\"$APP_PORT\"" >> .env

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PAT }}


      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: alonecat/photo-stock-frontend:latest